### ISSUE TITLE
Latest version in GitHub Marketplace isn't

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator-action#139]
Per https://github.com/marketplace/actions/linkinator, latest version is `v1.0.9`.

Per https://github.com/JustinBeckwith/linkinator-action/releases, it is `v1.10.2`.

Trusting Marketplace will send you down a road of confusion because the code you see doesn't match what's running.

**Comment by JustinBeckwith** [comment]
So I think I got this fixed.  I thought these updates would be automatic for each release, but I guess not :|
