### ISSUE TITLE
Node.js 16 actions deprecation warning

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator-action#174]
Hey, @JustinBeckwith!

>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: JustinBeckwith/linkinator-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Would you be so kind to update the action to Node.js 20 (maybe along with any deps)?

**Comment by JustinBeckwith** [comment]
Should be resolved with the latest version :)
