### ISSUE TITLE
Suggestion: Provide an option to show the links that are scanned in the action's output

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator-action#30]
The CLI does this by default and it's a nice way to confirm the expected links were checked.

Currently:

```text
Run JustinBeckwith/linkinator-action@v1
  with:
    paths: **/*.md
    markdown: true
    linksToSkip: node_modules/,test/,^https://github.com/.*/search\?q=,lib,style
    concurrency: 100
    recurse: false
    timeout: 0
Scanning http://localhost:5812/CONTRIBUTING.md
Scanning http://localhost:5812/doc/CustomRules.md
Scanning http://localhost:5812/doc/Rules.md
Scanning http://localhost:5812/example/good.md
Scanning http://localhost:5812/helpers/README.md
Scanning http://localhost:5812/example/bad.md
Scanning http://localhost:5812/README.md
Scanned total of 342 links!
```

See also: https://github.com/JustinBeckwith/linkinator/issues/213

**Comment by JustinBeckwith** [comment]
Thinking the solution to this one will probably be:
- Implement what we're talking about in https://github.com/JustinBeckwith/linkinator/issues/213
- Default to the `warning` setting
- Possibly expose a `verbosity` input for the action itself

**Comment by DavidAnson** [comment]
Thanks!

Any chance the output is truncated? In a test run, line 103 is: `Scanned total of 342 links!`. I'd expect that to be on line >= 342 in order for all of those scanned links to be listed. Or?

Example (if you can see it): https://github.com/DavidAnson/Workflows/runs/1624915279

**Comment by JustinBeckwith** [comment]
Ah - I think the total number of links right now includes skipped files.  Submitting a PR momentarily to fix that :)

**Comment by DavidAnson** [comment]
For reference, the tool I've been for this using saw 164 links in that same scenario: https://github.com/DavidAnson/Workflows/runs/1624915420

**Comment by JustinBeckwith** [comment]
Curious.   Could I trouble you for a minimal set of steps to try this with your repository?  I want to make sure I'm doing an apples to apples comparison.

**Comment by DavidAnson** [comment]
That tool may be wrong, but it's run by this workflow: https://github.com/DavidAnson/Workflows/blob/linkinator/.github/workflows/markdown-link-check.yml

You only care about the first section, markdownlint. The workflow for linkinator lives in the same directory. I pushed an empty commit last night to kick things off with your latest code. If you need to PR something to that branch to get another run, feel free.

**Comment by DavidAnson** [comment]
Oh, and this commit shows the changes to use linkinator CLI instead of Action: https://github.com/DavidAnson/Workflows/commit/6cc6e353186850547bae51f121d7cbb19e92d35e
