### ISSUE TITLE
Retry on timeout?

### ISSUE THREAD

**Issue by chingor13** [JustinBeckwith/linkinator-action#89]
We see a lot of `[0]` responses which are timeouts. Can we have an option to retry timeouts?

example: https://github.com/googleapis/nodejs-dialogflow-cx/pull/186/checks?check_run_id=3795247264

**Comment by bcoe** [comment]
https://github.com/JustinBeckwith/linkinator/pull/354 I added this functionality, I'm hoping it solves the problem for us.

We can reopen this issue if we're still bumping into issues.
